### ISSUE TITLE
Azure Functionsのテンプレート名が「WebHook + API」ではなく「Http trigger」

### ISSUE THREAD

**Issue by rukasakurai** [MicrosoftLearning/AZ-900T0xJA-MicrosoftAzureFundamentals#1]
# Module: 'モジュール 02 - コア Azure サービス'
#### Step: 3

現在はAzure Functionsのテンプレート名が「WebHook + API」ではなく「Http trigger」となっている

**Comment by LuongNguyen0906** [comment]
Hi, 

Can you please provide more details about bugs?

Thanks.

**Comment by wentingd** [comment]
Hi, I thought this is pretty straight forward: the current UI says "Http trigger" instead of "WebHook + API" as the Japanese version says.
If you take a look at the English version of this repo you can see how it should be changed very clearly...
https://github.com/MicrosoftLearning/AZ-900T0x-MicrosoftAzureFundamentals/blob/master/Instructions/Walkthroughs/08-Implement%20Azure%20Functions.md#task-2-create-a-http-triggered-function-and-test
